### ISSUE TITLE
[BUG] Änderung Auflösung

### ISSUE THREAD

**Issue by SebastianL-VM58** [stayathome1761/Client#108]
**Beschreibe den Fehler**
App wird zum zweiten Mal gestartet

**Um es nachzuvollziehen**
Die Schritte zum Fehler:
1. Öffnete HomeScreen 
2. Fehler enstanden: Auflösung passt nicht mehr.

**Was war erwartet**
Ich hätte erwartet, dass die Auflösung gleich bleibt

**Screenshots**
[Bug Auflösung.pdf](https://github.com/stayathome1761/Client/files/4364957/Bug.Auflosung.pdf)

**Smartphone (Bitte die Informationen ausfüllen):**
 - Gerät: Huawei Mate Pro20
 - OS: Android
 - Version 10

**Zusätzliches**
---

**Comment by karboe** [comment]
Can't reproduce
