### ISSUE TITLE
[BUG] Textfelder sind keine Pflichtfelder

### ISSUE THREAD

**Issue by westernheld** [stayathome1761/Client#111]
**Beschreibe den Fehler**
Textfelder sind keine Pflichtfelder

**Um es nachzuvollziehen**
Die Schritte zum Fehler:

**Was war erwartet**
Textfelder sind Pflichtfelder

**Screenshots**
Wenn möglich können auch Screenshots zum erklären des Problem hinzugefügt werden

**Smartphone (Bitte die Informationen ausfüllen):**
- Gerät: [Galaxy S10]
- OS: [Android 10]

**Zusätzliches**
Schreibe noch anderes zum Fehler hier auf

**Comment by prooxeydev** [comment]
ich bitte darum, dass die Beschreibung des Realeases durchgelesen wird und dann erst ein Issue gestellt wird.
