### ISSUE TITLE
[BUG]Weiter Button nicht sichtbar

### ISSUE THREAD

**Issue by westernheld** [stayathome1761/Client#132]
**Beschreibe den Fehler**
Weiter Button ist nach Start der App nicht sichtbar

**Um es nachzuvollziehen**
Die Schritte zum Fehler:
App geöffnet

**Was war erwartet**
Button ist sichtbar

**Screenshots**
Wenn möglich können auch Screenshots zum erklären des Problem hinzugefügt werden
![image](https://user-images.githubusercontent.com/1569381/77250257-032d4e00-6c47-11ea-8e56-b6b94b94e064.png)

**Smartphone (Bitte die Informationen ausfüllen):**
 - Gerät: [Samsung S7]
 - OS: [Android 8]

**Zusätzliches**
Schreibe noch anderes zum Fehler hier auf

**Comment by CaluvH** [comment]
Fixed with new release
