### ISSUE TITLE
[BUG] Homescene growing animation

### ISSUE THREAD

**Issue by rapus95** [stayathome1761/Client#181]
**Beschreibe den Fehler**
Was ist das?

**Um es nachzuvollziehen**
Frag Louis

**Was war erwartet**

**Screenshots**
![image](https://user-images.githubusercontent.com/5960902/77263702-33054180-6c99-11ea-9c37-8ddce420fb1b.png)

**Smartphone (Bitte die Informationen ausfüllen):**
- Realme OS

**Comment by prooxeydev** [comment]
<3
