### ISSUE TITLE
Credits == Impressum[BUG]

### ISSUE THREAD

**Issue by shendayan** [stayathome1761/Client#182]
**Beschreibe den Fehler**
Ich bin in die Settings gegangen und habe mir zuerst die Credits und dann das Impressum angesehen. Bei beiden Buttons, kommt die selbe Anzeige.

**Was war erwartet**
Credits und Impressum sollten unterschiedlich sein.

**Smartphone (Bitte die Informationen ausfüllen):**
 - Gerät: Huawei P30 Pro

**Comment by shendayan** [comment]
Das Selbe gilt für die Privacy Policy.

**Comment by CaluvH** [comment]
Will be done together with #183
