### ISSUE TITLE
Aufblitzen der Story beim 2. Start der App[BUG]

### ISSUE THREAD

**Issue by shendayan** [stayathome1761/Client#184]
**Beschreibe den Fehler**
App das 2. Mal gestartet, Ladescreen mit wachsendem Baum, dann für eine halbe Sekunde der Anfang der Story sichtbar, bevor der Setzling angezeigt wird.

**Um es nachzuvollziehen**
Die Schritte zum Fehler:
1. Öffnete die App
2. Fehler enstanden

**Was war erwartet**
Na dass man den Storybeginn nicht nochmal sieht :)

**Screenshots**
So schnell bin ich nicht 😄 

**Smartphone (Bitte die Informationen ausfüllen):**
 - Gerät: Huawei P30 Pro

**Comment by CaluvH** [comment]
Idea: We could use the Loading-Screen to check whether the PlayerPrefs are present. If yes, we can go directly to the HomeScreen otherwise we continue to the GardenSetup
